### ISSUE TITLE
help

### ISSUE THREAD

**Issue by shijun-XU** [Oulu-IMEDS/OAProgressionMR#2]
I would like to ask, for example tiulpin2019multimodal__labels.csv、contents.csv， where can I find these files? Can you share them? I would be very grateful.

**Comment by soupault** [comment]
Hi @shijun-XU. Apparently and unfortunately, OAI does not longer include `contents.csv` files in their data distribution. Those were, essentially, the index of all the imaging data (see the picture in https://github.com/Oulu-IMEDS/OAProgressionMR/issues/1 for a visual example). I am not allowed to redistribute the `contents.csv` files I have, and, at this point, they are outdated anyway.

I have not had time yet to investigate whether there is an alternative index in the latest version of the dataset. Thus, I suggest you check that and/or build a `contents`-like file yourself based on the DICOM-headers of the images.

`tiulpin2019multimodal__labels.csv` was generated using this script - https://github.com/Oulu-IMEDS/OAProgression/blob/master/oaprogression/metadata/oai.py, which calls to https://github.com/Oulu-IMEDS/OAProgression/blob/master/oaprogression/metadata/oai.py .
